### ISSUE TITLE
meetup: first meet-up, make it happen

### ISSUE THREAD

**Issue by profnandaa** [nodeschool/nairobi#2]
I would like us to have the first meetup at last, been long time coming! :sweat_smile: 

```
Date: TBD
Venue: TDB
Sponsors: Kazi+, DevC Nairobi (to-be-confirmed)
```

**Comment by profnandaa** [comment]
Whoever would like to present on anything cool for our first meeting, consider this a request-for-proposal (RFP), please post here the topic you would like to present on and a link to the abstract (preferably a README on your repo).

**Comment by mofax** [comment]
would love to talk about design systems.

**Comment by profnandaa** [comment]
@mofax -- sounds great. You can share abstract soonest?

**Comment by antosan** [comment]
> would love to talk about design systems.

@mofax We have our second event on Saturday, Feb 27, 2021. Please get in touch if you would like to give this talk at the event.

**Comment by mofax** [comment]
Sawa @antosan will check if I still have the material.

**Comment by profnandaa** [comment]
We can close this now that we already had meetup #1 ?
